"use client";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";
import Theme from "./theme";
import SideBar from "./components/SideBar/page";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Immunify",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/favicon.ico?v=4"],
    shortcut: ["/favicon.ico?v=4"],
  },
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isAuthPage =
    pathname === "pages/LoginPage" ||
    pathname === "pages/SignupPage" ||
    pathname === "pages/ForgotPassword";

  return (
    <html lang="en">
      <Theme>
        <body className={inter.className}>
          {isAuthPage ? children : <SideBar>{children}</SideBar>}

          <footer
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              height: "100px", // Adjust height as needed
            }}
          >
            @BalsomoPagueVillacis 2024
          </footer>
        </body>
      </Theme>
    </html>
  );
}
