"use client";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import "./globals.css";
import Theme from "./theme";
import SideBar from "./components/SideBar/page";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Immunify",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/favicon.ico?v=4"],
    shortcut: ["/favicon.ico?v=4"],
  },
};
const noSidebarPaths = {
  folders: ["mobilePages"],
  pages: ["/pages/LoginPage", "/pages/SignupPage", "/pages/ForgotPass"],
};

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const shouldHaveSidebar = () => {
    // Check if the path is in the excluded folders
    const inExcludedFolder = noSidebarPaths.folders.some((folder) =>
      pathname.startsWith(`/${folder}`)
    );

    // Check if the path is an excluded page
    const isExcludedPage = noSidebarPaths.pages.includes(pathname);

    return !inExcludedFolder && !isExcludedPage;
  };

  return (
    <html lang="en">
      <Theme>
        <body className={inter.className}>
          {shouldHaveSidebar() ? (
            <>
              <SideBar />
              <main>{children}</main>
            </>
          ) : (
            children
          )}

          <footer
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              height: "100px", // Adjust height as needed
            }}
          >
            @BalsomoPagueVillacis 2024
          </footer>
        </body>
      </Theme>
    </html>
  );
}
