import { Inter } from "next/font/google";
import "./globals.css";
import Theme from "./theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Immunify",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/favicon.ico?v=4"],
    shortcut: ["/favicon.ico?v=4"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Theme>
        <body className={inter.className}>
          {children}

          <footer
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              height: "100px", // Adjust height as needed
            }}
          >
            @BalsomoPagueVillacis 2024
          </footer>
        </body>
      </Theme>
    </html>
  );
}
