name: Send Reminder Emails

on:
  schedule:
    - cron: "5 0 * * *" # Runs daily at midnight

jobs:
  send-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Trigger Email API
        run: curl -X POST http://localhost:3000/pages/api/send-emails
