name: Send Reminder Emails

on:
  schedule:
    - cron: "30 1 * * *"  # Runs daily at 00:05 UTC
  workflow_dispatch:

jobs:
  send-emails:
    runs-on: ubuntu-latest
    env:
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}  # Your deployed app URL
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          
      - name: Install Dependencies
        run: npm install
        
      - name: Debug Info (Masked)
        run: |
          echo "Using APP URL: $NEXT_PUBLIC_APP_URL" | sed 's/[[:alnum:]]/<hidden>/g'
          echo "Resend API Key is set: ${{ secrets.RESEND_API_KEY != '' }}"
        
      - name: Trigger Email API
        run: |
          curl --fail -X POST "${NEXT_PUBLIC_APP_URL}/api/send-emails" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.RESEND_API_KEY }}" \
          -d '{}' \
          -v
